import gdext
import classes/gdBoidController3D
import classes/gdBoidSpawner3D
import classes/gdBoidModule3D
import classes/gdBoidRuleCohesion3D
import classes/gdBoidRuleSeparation3D
import classes/gdBoidRuleAvoidGrid3D


GDExtensionEntryPoint
